-- init.sql
CREATE DATABASE IF NOT EXISTS CONNECTS;
CREATE USER IF NOT EXISTS 'CONNECTS'@'localhost' IDENTIFIED BY 'Connects';
GRANT ALL PRIVILEGES ON CONNECTS.* TO 'CONNECTS'@'localhost';
FLUSH PRIVILEGES;
USE CONNECTS
CREATE TABLE role (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);
INSERT INTO role (id, name) VALUES (1, 'ROLE_USER'), (2, 'ROLE_TEACHER'), (3, 'ROLE_ADMIN');
EXIT;